### ISSUE TITLE
[SUGGESTION] Horse Armor

### ISSUE THREAD

**Issue by Sunconure11** [Buuz135/ArmoreableMobs#13]
A number of mods add their own variants of horse armor, and maybe we could allow configuration of scripts to let them spawn on some hostile horse variants/equivalent?

**Comment by Sunconure11** [comment]
@Buuz135 What ever became of this?

**Comment by Witixin1512** [comment]
You can give horses an armor in their Chest Equipmentslot. As long as it extends ArmorHorseItem (1.18) or renders it themselves, it will appear on a horse.

```zenscript
new ArmorGroup("horse_showcase")
.inSlot(<constant:minecraft:equipmentslot:chest>, <item:minecraft:horse_armor_diamond>);
.setWeight(2.0)
.register(<entitytype:minecraft:horse>);
```

![image](https://user-images.githubusercontent.com/73248264/165551135-14d4d191-38f8-4248-b021-b0a9f7bb5917.png)

**Comment by Sunconure11** [comment]
Ah

**Comment by Sunconure11** [comment]
What slot do saddles fall under?

**Comment by Witixin1512** [comment]
It's part of the Horse's `inventory`, not armor
