### ISSUE TITLE
[SUGGESTION] Trinkets/Curios compat

### ISSUE THREAD

**Issue by Sunconure11** [Buuz135/ArmoreableMobs#17]
Some mods have trinkets or curios that render on a player. I think they could make a perfect fit here.

**Comment by Witixin1512** [comment]
Curios is only for players isn't it?

**Comment by Sunconure11** [comment]
Honestly, this idea came to me with seeing stuff like BA+'s capes and what not

**Comment by Witixin1512** [comment]
No idea what BA+'s capes is, but capes or similar aren't well looked on because it's not something Mojang want people to make.
Anyway, i'll look into Trinkets for Fabric 1.18, as that seems to be on all Entities.
