### ISSUE TITLE
【fabric1.18.2】When left hanging and armomobs exist at the same time, armomobs cannot be loaded in the game normally

### ISSUE THREAD

**Issue by LILPRINCES** [Buuz135/ArmoreableMobs#18]
When left hanging and armomobs exist at the same time, armomobs cannot be loaded in the game normally

game version:
[LeftHanging](https://www.curseforge.com/minecraft/mc-mods/left-hanging)-fabric-1.18.2-3.2.0.2
ArmoreableMobs-fabric-1.18.2-1.0.5
CraftTweaker-fabric-1.18.2-9.1.177
IngredientExtensionAPI-fabric-1.18.2-2.0.6
FauxCustomEntityData-fabric-1.18.2-1.0.4
fabric-api-0.58.0+1.18.2

**Comment by Witixin1512** [comment]
Will be fixed in the newest update
