### ISSUE TITLE
Armor drops although drop chance is 0.0

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/ArmoreableMobs#4]
Hey! I've experienced that armor pieces can drop, although their drop chance is set to 0.0. I believe it's an unintended interaction with Looting. In addition, it seems the drop chance increases significantly, possibly a flat rate, when the given mob is killed with looting.

**Comment by Buuz135** [comment]
Just as a heads up, this will require big changes that I dont want to do right now, but it will come soon ™️

**Comment by rootmenu** [comment]
@NillerMedDild I looked up the looting modifier. It's not an unintended interaction, just the way looting works. Basically its a function: if a random value between 0 and 1 - level of looting * 0.01 is less than the drop chance, the item drops. 

A simple (and working) solution is to set the drop chance lower than 0. I tested with a drop chance of -1 and a looting 10 sword and no armor dropped.

**Comment by NielsPilgaard** [comment]
Ah cool, thanks!
