### ISSUE TITLE
[Request] Drop on player kill only config

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/ArmoreableMobs#5]
Hey! 
I'd like to request an additional, optional boolean parameter, for setting equipment to drop on player kill only. I'm thinking it should work like this:
`armorGroup.addArmor(ArmorHandler.createArmorSlot("head", <botania:terrasteelhelm>, 1, 0.003, false));`
would disable the drop from anything but player kills.

Additional, a fake player / real player divided drop chance would be awesome, for setting the chance of getting certain armors from mob spawners.

What do you think?

**Comment by Buuz135** [comment]
Just as a heads up, this will require big changes that I dont want to do right now, but it will come soon ™️

**Comment by NielsPilgaard** [comment]
Sweet, thank you :D
