### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by rooben777** [Buuz135/ArmoreableMobs#6]
Hey guys, I have been looking for a mod like this for like 3 days... and I finaly found it! so I hoped it to be something rather simple with a config file which will allow me to easly change things.. but I was horrified to find out that I need to create an entire script to actually use this, and I have absolutly no idea how to do that.. basicly my kid wants zombies and skeletons to have a chance to spawn with vanilla armors on them, (preferably hats so they wont burn in sulight) if you guys could just create a script like that and upload it to dropbox that would be amazing!! I really dont want to led the boy down.. :(

**Comment by Buuz135** [comment]
I'm sorry but having everything done via config would be a terrible nightmate
